version: '3.9'
services:
  sender-1:
    image: alpine
    volumes:
      - ./send_requests.sh:/send_requests.sh
    command: /bin/sh -c "apk add --no-cache curl && ip a && /bin/sh /send_requests.sh"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.101
  
  sender-2:
    image: alpine
    volumes:
      - ./send_requests.sh:/send_requests.sh
    command: /bin/sh -c "apk add --no-cache curl && ip a && bin/sh /send_requests.sh"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.102
      
  sender-3:
    image: alpine
    volumes:
      - ./send_requests.sh:/send_requests.sh
    command: /bin/sh -c "apk add --no-cache curl && ip a && bin/sh /send_requests.sh"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.103


networks:
  mynetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
